# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleApp
  #pod "momosdk-swift" , :path => "../../../momosdk-swift"
  pod "momosdk-swift", :git => "https://github.com/momodevelopment/momosdk-swift.git", :branch => "master", submodules: true
end
